version: "3.7"
services:
  # First develop then integrate in .yml
  #scala_api:
    #build: 
    #  context: .
    #  dockerfile: Dockerfile
    #ports:
    #  - "8080:8080"
    #volumes: 
    #  - ./:/root/src
    # enable interactive shell
    #entrypoint: bash
    # -i interactive
    #stdin_open: true
    # -t tty shell
    #tty: true
  mongodb:
    build: 
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  couchdb:
    build: 
      context: ./couchdb
      dockerfile: Dockerfile
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb/data:/opt/couchdb/data
volumes:
  mongodata: